### ISSUE TITLE
Improving inference speed

### ISSUE THREAD

**Issue by valentynbez** [bioinf-mcb/DeepFRI#2]
For large datasets prediction time is time-sensitive. For now, we can speak abt the functional annotation of `10e6` proteins.  

Possible solutions:  
- porting weights to the analogous network in `pytorch` (will be more future-proof) 
- profiling and identifying bottlenecks with `valgrind` https://valgrind.org/
-  porting time-sensitive pieces of code to C (Cython) or Rust (PyO3)

**Comment by wwydmanski** [comment]
We've decided to add a separate fast prediction route in ONNX (using your code, lol) in #3
